### ISSUE TITLE
Make taro without command alias for taro ps

### ISSUE THREAD

**Issue by StanSvec** [taro-suite/taro#4]
When taro is executed without any command then run -> `taro ps`

**Comment by ayush714** [comment]
Can you give me more detail?

**Comment by StanSvec** [comment]
Thanks for considering your contribution to the project. Please keep it mind that it hasn't been fully prepared for collaborations yet. However feel free to participate already in anything you'd like.
---
## Problem
This task is very simple. At the moment you can execute taro without specifying a command (like ps, hist, etc.). If you execute in command line simply `taro` or alternatively `python -m taroapp` you'll get an error:
`Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/stans/Projects/taro-suite/taro/taroapp/__main__.py", line 42, in <module>
    main(sys.argv[1:])
  File "/home/stans/Projects/taro-suite/taro/taroapp/__main__.py", line 24, in main
    cmd.run(args_ns)
  File "/home/stans/Projects/taro-suite/taro/taroapp/cmd/__init__.py", line 5, in run
    action = args.action.replace('-', '_')
AttributeError: 'NoneType' object has no attribute 'replace'`

## Solution
Executing simply `taro` (without any command) must print running job instances. In other words executing `taro` must be equivalent (alias) to `taro ps` command.
